[package]
name = "vaultic"
version = "0.1.0"
edition = "2024"
authors = ["SoftDryzz"]
description = "Secure your secrets. Sync your team. Trust your configs."
license = "MIT"
repository = "https://github.com/SoftDryzz/vaultic"
keywords = ["env", "secrets", "encryption", "cli", "dotenv"]
categories = ["command-line-utilities", "cryptography"]

[dependencies]

[dev-dependencies]
